homework_10/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path(
        "",
        views.index_view,
        name="index",
    ),
    path(
        "categories/",
        views.categories_with_posts,
        name="categories-with-posts",
    ),
    path(
        "list/",
        views.PostListView.as_view(),
        name="list",
    ),
    path(
        "detail/<int:pk>/",
        views.PostDetailView.as_view(),
        name="detail",
    ),
]

homework_10/settings/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("posts/", include("posts.urls")),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

homework_10/posts/models.py
from django.db import models


class Category(models.Model):
    class Meta:
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    text = models.CharField(max_length=1000)

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="posts",
    )

    def __str__(self):
        return self.title

homework_10/posts/views.py
from django.http import HttpRequest
from django.shortcuts import render
from .models import Category, Post
from django.views.generic import (
    ListView,
    DetailView,
)


def index_view(request):
    posts = (
        Post
        .objects
        .select_related("category")
        .all()
    )
    context = {
        "posts": posts,
    }
    return render(
        request,
        "posts/posts-list.html",
        context,
    )


def categories_with_posts(request: HttpRequest):
    context = {
        "categories": (
            Category
            .objects
            .prefetch_related("posts")
            .all()
        )
    }
    return render(
        request,
        "posts/categories-with-posts.html",
        context,
    )


class PostListView(ListView):
    model = Post


class PostDetailView(DetailView):
    model = Post

homework_10/posts/templates/posts/categories-with-posts.html
{% extends 'base.html' %}

{% block title %}
  Categories w/ posts
{% endblock %}

{% block body %}
  <h1>Categories</h1>
  <h2>With posts</h2>

  {% if categories %}
    <ul>
      {% for category in categories %}
        <li>
          <strong>{{ category }}</strong>
          <ul>
            {% for post in category.posts.all %}
              <li>{{ post }}</li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h3>No categories yet</h3>
  {% endif %}

  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
  {{object.title}}
{% endblock %}

{% block body %}
  <h1>{{object.category.name}}</h1>
    <strong>
      {{object.title}}
    </strong>
    <br><br>
    {{object.text}}
    <br><br>
    <div>
      <a href="{% url 'posts:list' %}">Back to list</a>
    </div>
  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block title %}
  Posts list
{% endblock %}

{% block body %}
  <h1>Posts:</h1>
  {% if object_list %}
    <ul>
      {% for post in object_list %}
        <li>
          <a href="{% url 'posts:detail' pk=post.pk %}">
              {{ post.title }}
          </a>
          <br>
          <em>{{ post.text }}</em>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>No posts yet!</h2>
  {% endif %}
<p></p>
  {{some_var}}
<p></p>
  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/posts/templates/posts/posts-list.html
{% extends 'base.html' %}

{% block title %}
  Posts
{% endblock %}

{% block body %}
  <h1>Posts:</h1>
  {% if posts %}
    <ul>
      {% for post in posts %}
        <li>
          <strong>{{ post.title }}</strong> <em>({{ post.category.name }})</em>
          <br>
          {{ post.text }}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>No posts yet!</h2>
  {% endif %}

  {% include 'common/footer-common.html' %}
{% endblock %}

homework_10/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <title>{% block title %}
  	Base title
  {% endblock %}</title>
</head>
<body>
    <div class="container my-3 mt-5 p-1">
    {% block body %}
        Base body
    {% endblock %}
    </div>
</body>
</html>

homework_10/templates/common/footer-common.html
<div>
  <a href="{% url 'index' %}">Back to index</a>
</div>

homework_10/templates/index.html
{% extends 'base.html' %}

{% block title %}
  Posts Homepage
{% endblock %}

{% block body %}
  <h1>Welcome to Posts!</h1>
  <ul>
    <li>
      <a href="{% url 'posts:index' %}">Posts</a>
    </li>
    <li>
      <a href="{% url 'posts:categories-with-posts' %}">Categories</a>
    </li>
    <li>
      <a href="{% url 'posts:list' %}">Posts list</a>
    </li>
  </ul>
{% endblock %}